# ==========================
# Stage 1: Install Dependencies
# ==========================
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm ci

# ==========================
# Stage 2: Build the Application
# ==========================
FROM node:20-alpine AS builder
WORKDIR /app

# 1. Declare ALL build arguments needed for Next.js build & Prisma
ARG DATABASE_URL
ARG DIRECT_URL
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ARG CLERK_WEBHOOK_SECRET
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG IMAGEKIT_PUBLIC_KEY
ARG IMAGEKIT_PRIVATE_KEY
ARG IMAGEKIT_URL_ENDPOINT
ARG INNGEST_EVENT_KEY
ARG INNGEST_SIGNING_KEY
ARG NEXT_PUBLIC_CURRENCY_SYMBOL
ARG ADMIN_EMAIL

# 2. Set them as ENV so Next.js/Prisma can read them during build
ENV DATABASE_URL=${DATABASE_URL}
ENV DIRECT_URL=${DIRECT_URL}
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
ENV CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
ENV CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
ENV STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
ENV STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
ENV IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
ENV IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
ENV IMAGEKIT_URL_ENDPOINT=${IMAGEKIT_URL_ENDPOINT}
ENV INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY}
ENV INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY}
ENV NEXT_PUBLIC_CURRENCY_SYMBOL=${NEXT_PUBLIC_CURRENCY_SYMBOL}
ENV ADMIN_EMAIL=${ADMIN_EMAIL}

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Ensure public folder exists to prevent COPY errors in the runner stage
RUN mkdir -p /app/public

# Generate Prisma Client (now has access to DATABASE_URL)
RUN npx prisma generate

# Build Next.js
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# ==========================
# Stage 3: Production Runner
# ==========================
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the standalone output generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy Prisma files so the app can interact with the DB at runtime
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/@prisma ./node_modules/@prisma
#COPY --from=builder --chown=nextjs:nodejs /app/prisma.config.ts ./prisma.config.ts

# NEW: Copy the entrypoint script and make it executable
COPY --chown=nextjs:nodejs entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# ✅ NEW: Use the entrypoint script instead of CMD
ENTRYPOINT ["./entrypoint.sh"]