sonar.projectKey=ayoub404-mak_voltcart
sonar.organization=ayoub404-mak

sonar.sources=.
sonar.exclusions=node_modules/**,.next/**,coverage/**,infrastructure/**

sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info